spring:
  datasource:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"
    url: jdbc:mysql://localhost:3306/livraisons?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: colis
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8098/eureka/