spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admins?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: admins
server:
  port: 8095
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8098/eureka/
